require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

Style/MutableConstant:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/NestedGroups:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ImplicitSubject :
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Exclude:
    - 'spec/rails_helper.rb'

Rails/HasManyOrHasOneDependent:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
    - 'spec/**/*.rb'
    - 'db/**/*.rb'
    - 'config/**/*.rb'

AllCops:
  NewCops: enable
  Exclude:
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - '.circleci/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'log/**/*'
    - 'test/**/*'
    - 'config/**/*'
    - 'spec/factories/*'
    - 'config/initializers/devise.rb'
    - 'db/migrate/*'
    - 'db/schema.rb'
